name: G0ph3r

url: https://samkeet.github.io/

author: Samkeet Shah

theme: jekyll-theme-minima

paginate: 5

permalink: pretty

exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
